<?php
/**
* @var $block \Acodesh\Order\Block\Adminhtml\Order\View\Tab\CustomTab
*/
?>

<div class="fieldset-wrapper order-information">
    <div>
       <h2><?php echo __('Custom Tab'); ?></h2>
    </div>
    <div class="fieldset-wrapper-title">
        <span class="title"><?php echo __('Custom Field. For Order') ?></span>
    </div>
    <form class="form contact"
        action="<?php echo $block->getFormAction(); ?>"
        id="submit_custom_field"
        data-mage-init='{"validation":{}}'>

        <table class="admin__table-secondary">
            <tbody>
                <?php echo $block->getChildHtml(); ?>
                <tr>
                    <th><?php echo __('Order ID:') ?></th>
                    <td><?php echo $block->getOrderIncrementId(); ?></td>
                </tr>
                <tr>
                    <th><?php echo __('Add Custom Field:') ?></th>
                    <td><input name="custom_field" id="custom_field" value="<?php echo $block->getCustomField(); ?>" class="input-text required" type="text" data-validate="{required:true}"/></td>
                    <input name="order_id" id="order_id" value="<?php echo $block->getOrderId(); ?>"  type="hidden"/>
                </tr>
                    <tr>
                        <td colspan="2">
                            <button id=''><?php echo __('Save Information');?></button>
                        </td>
                    </tr>
            </tbody>
        </table>
    </form>
</div>

<script>
require(['jquery', 'mage/validation'],function($){
    var dataForm = $('#submit_custom_field');
    dataForm.mage('validation', {}); 
    jQuery(document).ready(function() {
        jQuery("#submit_custom_field").submit(function(){
            var status = dataForm.validation('isValid'); 
            if(status) {
                    var custom_field_value = jQuery("input[name='custom_field']").val();
                    var order_id_value = jQuery("input[name='order_id']").val();
                    var url = "<?php echo $block->getBaseUrl();?>";
                    jQuery.ajax({
                        url: url,
                        type: "POST",
                        data: {custom_field:custom_field_value, order_id:order_id_value},
                        showLoader: true,
                        cache: false,
                    success: function(response){
                    }
                });
            } else {
            }   
        return false;
        });
    });
});
</script>
